spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop;MVCC=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jap:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        formate_sql: true

logging:
  level:
    org.hibernate.SQL: debug